flowchart TD
    n0["Without Thread"]
    n1["Zinc electroplated FelZn 12p F4- AC- STD 6767K"]
    n2["Hose"]
    n3["M6 Zinc electroplated FelZn Sp F4- AC- STD"]
    n4["With Thread"]
    n5["M6 Zinc electroplated FelZn 8p F4- AC- STD"]
    n6["M6 Zinc electroplated FelZn 8p F4- AC- STD"]
    n0 --> n1
    n2 --> n4
    n2 --> n0
    n4 --> n5
    n4 --> n3
